apiVersion: v1
kind: Service
metadata:
  name: api-gateway-service
  namespace: ai-monitor
  labels:
    app: api-gateway
spec:
  selector:
    app: api-gateway
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
  type: LoadBalancer