apiVersion: v1
kind: Service
metadata:
  name: auto-scaler-service
  namespace: ai-monitor
  labels:
    app: auto-scaler
spec:
  selector:
    app: auto-scaler
  ports:
  - port: 8001
    targetPort: 8001
    protocol: TCP
  type: ClusterIP