name: Simple CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  # Code quality and testing
  ci:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        cache: 'pip'

    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install -r requirements.txt

    - name: Code formatting check
      run: black src/ tests/ --check --diff

    - name: Run linting
      run: flake8 src/ tests/

    - name: Type checking
      run: mypy src/

    - name: Run tests with coverage
      run: |
        pytest tests/ -v --cov=src --cov-report=term-missing

    - name: Security check
      run: |
        pip install bandit
        bandit -r src/ -f json -o bandit-report.json || true

  # Build Docker image
  build:
    runs-on: ubuntu-latest
    needs: ci
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Build Docker image
      run: |
        docker build -t ai-monitor:latest .
        docker images

    - name: Test Docker image
      run: |
        docker run --rm -d --name test-container -p 8080:8080 ai-monitor:latest
        sleep 10
        curl -f http://localhost:8080/health || exit 1
        docker stop test-container